version: "3.9"

services:
  
  django_server:
    build: .
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    platform: linux/x86_64
   
